services:
  open-overleaf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-overleaf
    ports:
      - "3201:8080"
      - "3100:3100"
      - "3202:3202"
    env_file:
      - .env.local
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 5120
        hard: 5120
    deploy:
      resources:
        limits:
          memory: 2G
